version: '3'

#서비스들의 이름은 임의로 지어도 됨 : 아래는 backend라고 했지만 다른 이름이어도 상관 없음
#그러나 서비스 아래의 내용들(image 등등... 은 정해진 형식임)
services:
  backend:
    image: ogolgye/inspire-monolithic
    container_name: monolithic-backend-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://lgcns-sglim.cb66yg44ot33.us-east-2.rds.amazonaws.com:3306/inspire?useSSL=true&verifyServerCertificate=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
      # JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_SHOW_SQL: true
      # redis 
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8888:8888"
    # depends_on은 컨테이너 실행 순서를 정의 : database와 redis가 실행 후 backend가 실행
    depends_on:
      # - database
      - redis
    restart: always

  # AWS RDS 사용시 제거(Container로 안쓰고 RDS걸 쓸거니까)
  # database:
  #   image: ogolgye/inspire-mariadb
  #   container_name: monolithic-mariadb-container
  #   ports:
  #     - "6033:3306"
  #   environment:
  #     MARIADB_USER: root
  #     MARIADB_ROOT_PASSWORD: 123456789
  #     MARIADB_DATABASE: inspire

  redis:
    image: ogolgye/inspire-redis
    container_name: monolithic-redis-container
    ports:
      - "6379:6379"
    restart: always
