name : deploy order

on:
  # main이라는 브랜치에 push 또는 pull request가 발생했을 때 파이프라인이 동작 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


#내부에 job들은 여러개 있을 수 있음      
jobs:
  build-and-deploy: # job의 이름(build-and-deploy는 내가 지은 이름)
    
    #runner
    runs-on: ubuntu-latest # 어떤 환경에서 job이 실행될 것인지(ubuntu-latest, windows-latest, macos-latest)
    steps:
      - name: Check out github
        uses: actions/checkout@v2 # github에서 코드를 체크아웃하는 액션
        
      - name : install kubectl
        uses: azure/setup-kubectl@v1 # kubectl 설치 액션
        with:
          version: 'latest' # kubectl의 버전(latest, 1.20.0 등)

  # build-and-push: # job의 이름
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name : Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-2

  #     - name: Log in to Amazon ECR
  #       uses: aws-actions/amazon-ecr-login@v1

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         push: true
  #         tags: 447839931800.dkr.ecr.us-east-2.amazonaws.com/order-sglim-backend:latest

  #     - name: Deploy to Kubernetes
  #       uses: appleboy/k8s-deploy@v1.0.0
  #       with:
  #         kubeconfig: ${{ secrets.KUBECONFIG }}
  #         manifests: k8s/order_deployment.yml